
#ifndef ALARM_DEF_H
#define ALARM_DEF_H

#include "Alarms.h"

/* custom alamrs */
#define ALARM_DEF_TENTH_SECOND (ALARM_DEF_10)
#define ALARM_DEF_SECOND (ALARM_DEF_11)
#define ALARM_DEF_HUNDRED_MS (ALARM_DEF_12)

#define ALARM_DEF_ERROR (ALARM_DEF_20)
#define ALARM_DEF_WARNING (ALARM_DEF_21)

#define ALARM_DEF_KILL (ALARM_DEF_27)
#define ALARM_DEF_STOP (ALARM_DEF_28)
#define ALARM_DEF_RESUME (ALARM_DEF_29)

#endif
